### ISSUE TITLE
Upgrade dependency to basic_utils ^2.6.3

### ISSUE THREAD

**Issue by wahyubucil** [adaptant-labs/vin-decoder-dart#2]
I've version solving failed. I want to use the latest `json_annotation`. I use `validators` and it depends on `vin_decoder` that depends on old `basic_utils` (the latest `basic_utils` already upgrade the json_annotation)

This is the error example: https://github.com/dart-league/validators/issues/20

Thanks in advance :)

CC: @pmundt

**Comment by slavap** [comment]
@pmundt Please upgrade.
I cannot upgrade json_annotation, because vin_decoder 0.1.2 depends on basic_utils ^2.5.4
