### ISSUE TITLE
null safety version.

### ISSUE THREAD

**Issue by bsutton** [adaptant-labs/vin-decoder-dart#5]
Gentfolk,
what's the chance of getting a null safety version released?

I'm using the validators package which depends on vin-decoder which is stopping my moving to a full nnbd release for my project DCli.

A nnbd release would be greatly appreciated.

**Comment by pmundt** [comment]
Thanks for the report, I wasn't aware we were blocking the validators project. I'll set aside some time for this in the next couple of days and prepare a null safety version.

**Comment by bsutton** [comment]
Thanks

**Comment by pmundt** [comment]
A `0.2.0-nullsafety` pre-release has now been published.
