### ISSUE TITLE
 Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.

### ISSUE THREAD

**Issue by MedwinCorreo** [adaptant-labs/vin-decoder-dart#6]
![image](https://user-images.githubusercontent.com/16618565/110076160-fc97d800-7dbe-11eb-9f92-20e86ed15220.png)

`/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.3/lib/src/nhtsa_model.dart:89:37: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    final response = await http.get(path);`
    
    pls update

**Comment by pmundt** [comment]
Thanks, this was already fixed in the 0.2.0-nullsafety version. Could you please try with this?

**Comment by pmundt** [comment]
Ok, I have now cut new stable and pre-releases. Please use 0.1.4+1 if you require a stable release, or 0.2.1-nullsafety if you plan to have null safety enabled in your application.
